### ISSUE TITLE
Integrate InVEST's pour point detection with pygeoprocessing's?

### ISSUE THREAD

**Issue by phargogh** [natcap/pygeoprocessing#152]
With PR #151 merged, we now have two implementations of pour point detection:

* One in [`pygeoprocessing.routing`](https://github.com/natcap/pygeoprocessing/blob/main/src/pygeoprocessing/routing/routing.pyx#L4079)
* And one in [`natcap.invest.delineateit`](https://github.com/natcap/invest/blob/846fef97762ed23b1c3053d8b96b390c8dbb962f/src/natcap/invest/delineateit/delineateit.py#L634)

When comparing the two implementations, I noticed that @emlys 's implementation in DelineateIt runs in 1/3 the time of the implementation in pygeoprocessing that was recently merged.  [Here's a gist](https://gist.github.com/phargogh/d8ee8935ac1a5ead507cee601720d45b) comparing the two DEMs (and let me know if you'd like the Colombia DEM to try this out on).  Here are the mean runtimes (from n=5 runs) for two rasters running each of these  implementations:

```
Colombia DEM (15030 x 20631 pixels)
delineateit mean: 10.326407289505005s
pygeoprocessing mean: 31.769051218032835s

Gura DEM (1939 x 603 pixels)
delineateit mean: 0.031762552261352536s
pygeoprocessing mean: 0.09338397979736328s
```

I see that #151 has already been merged, but this difference in timing makes me wonder where the speedup is and if there's a key part of the InVEST implementation that can be integrated to grant the same speedup.

**Comment by richpsharp** [comment]
Hi both, thanks for this and especially the timings. I fixed the runtime performance and if my timings are right I think this implementation outperforms the routedem implementation in the above linked issue, though I didn't time it directly.

In terms of architecture, I intended `routedem` to be the module that exposes PyGeoprocessing routing functions to an InVEST user, specifically through the UI. But of course I don't maintain that anymore and intent and use can change, so I'm game for that.

For context, I needed an outlet flow detection implementation that hour (different story) and didn't think to look in InVEST. If I had known it was in InVEST it would have been an additional dependency/compile step to include it, and I'd be bringing ALL the invest models along just to use one hydrological function. Totally possible of course but it's conceptionally loopy.

But there's still a use case for putting core raster processing in InVEST but it would be something directly useful to a specific InVEST model and not useful outside of that context. NDR is an example of that as it needs custom code to saturate downstream nutrient flow. That wouldn't be something useful outside of NDR by itself.

It sort of raises the question of what's the design intent of `delineateit`? Because given that context it's odd that `delineateit` exists in InVEST at all and not in PyGeoprocessing. But the reason for that is also a little handwavy -- we don't want to add a whole UI to PyGeoprocessing, and InVEST already had a UI, so we just stuck it in there. That's fine with me since InVEST is already so tightly linked to PyGeoprocessing to begin with.

Anyway, that's my context and handwavy design intent for that. Whadda think? Any sea change here, or are we good?

**Comment by richpsharp** [comment]
p.s. @phargogh, if you care, and do take a look at this, would you mind running your same timings with those same data on this implementation?

**Comment by phargogh** [comment]
> p.s. @phargogh, if you care, and do take a look at this, would you mind running your same timings with those same data on this implementation?

The same timings on the same datasets are now:

```
Colombia DEM (15030 x 20631 pixels)
delineateit mean: 10.459819746017455s
pygeoprocessing mean: 6.512260007858276s

Gura DEM (1939 x 603 pixels)
delineateit mean: 0.039636850357055664s
pygeoprocessing mean: 0.038440513610839847s
```

So the Colombia DEM now has a ~38% speedup vs the current delineateit implementation, and the Gura DEM's speedup is negligible.

**Comment by phargogh** [comment]
> But the reason for that is also a little handwavy -- we don't want to add a whole UI to PyGeoprocessing, and InVEST already had a UI, so we just stuck it in there.

This is true about the UI, but I think the basic use case is still the same for both: the functions they provide are related to InVEST.  An alternative way to express this that involves a specific person for a use case: Stacie uses these in her analyses.  As I understand it, Stacie uses RouteDEM to get a better handle on TFA, and uses DelineateIt to delineate watersheds for use in InVEST-related analyses and non-InVEST related analyses.  That doesn't necessarily mean that it needs to be a UI in InVEST, though.

> But there's still a use case for putting core raster processing in InVEST but it would be something directly useful to a specific InVEST model and not useful outside of that context. NDR is an example of that as it needs custom code to saturate downstream nutrient flow. That wouldn't be something useful outside of NDR by itself.
> 
> It sort of raises the question of what's the design intent of delineateit? Because given that context it's odd that delineateit exists in InVEST at all and not in PyGeoprocessing.

Is the question here why there's a part of DelineateIt that's not in pygeoprocessing?  If so, it's because I had assumed that model/tool-specific should be addressed with the usual rule-of-3 approach we've been taking.  And there's some precedent for this as well given that Scenic Quality's `viewshed` is a geoprocessing operation, yet is still in InVEST.

So maybe a related question here (and certainly something I'd love for us to figure out) is what the line between the two libraries should be: when something should be developed from the get-go as a part of pygeoprocessing.

**Comment by richpsharp** [comment]
> Is the question here why there's a part of DelineateIt that's not in pygeoprocessing? If so, it's because I had assumed that model/tool-specific should be addressed with the usual rule-of-3 approach we've been taking. And there's some precedent for this as well given that Scenic Quality's `viewshed` is a geoprocessing operation, yet is still in InVEST.

Yep I see, outlet detection from the InVEST standpoint is some kind of tool that Stacie would use. I hadn't thought of it that way. On my end outlet detection is a core seeding algorithm in a lot of pipelines I use and I've done it way more than 3 times. It's nto an output in of itself I would find useful. This was the final time when I was like I am tired of writing this thing into every pipeline I have and then having to add a `setup.py` and turn it into a whole compiled module just to do some quick run of something. From my perspective outlet detection is an old, tired, and useful algorithm to have in pgp.

> So maybe a related question here (and certainly something I'd love for us to figure out) is what the line between the two libraries should be: when something should be developed from the get-go as a part of pygeoprocessing.

I feel like what we did here is okay except we should have had this conversation in the original PR. To me that's the place to discuss if something should get merged in and why... We could have addressed the runtime performance directly there and if there was a question of the need of an outlet detection algorithm in pgp, I could have provided more evidence for that too.

Is that okay? I feel like it's okay.

**Comment by emlys** [comment]
> I feel like what we did here is okay except we should have had this conversation in the original PR. To me that's the place to discuss if something should get merged in and why... We could have addressed the runtime performance directly there and if there was a question of the need of an outlet detection algorithm in pgp, I could have provided more evidence for that too.

I should have addressed this more directly in the original PR... I figured it makes sense for the algorithm to go in pygeoprocessing, and that the delineateit feature would get replaced, so it would essentially be a UI for the pgp function. I don't see any problem with having it both places as long as the code isn't duplicated, since we seem to have use cases for both (Stacie using it thru invest and Rich using it in other pipelines). But I didn't actually say any of those assumptions :/ Sorry for the extra PR and confusion!

**Comment by phargogh** [comment]
> Rich:
> Yep I see, outlet detection from the InVEST standpoint is some kind of tool that Stacie would use. I hadn't thought of it that way. On my end outlet detection is a core seeding algorithm in a lot of pipelines I use and I've done it way more than 3 times. ... From my perspective outlet detection is an old, tired, and useful algorithm to have in pgp.

Oh interesting ... I hadn't known that you had implemented this before.  This came up for the first time for us as a part of thinking about subwatershed delineation, another request from Stacie.

> Rich: 
> I feel like what we did here is okay except we should have had this conversation in the original PR. To me that's the place to discuss if something should get merged in and why... We could have addressed the runtime performance directly there and if there was a question of the need of an outlet detection algorithm in pgp, I could have provided more evidence for that too.
>
> Emily:
> I should have addressed this more directly in the original PR... I figured it makes sense for the algorithm to go in pygeoprocessing, and that the delineateit feature would get replaced, so it would essentially be a UI for the pgp function. 

So I think what I'm hearing is that if ever we have a function that feels like a core geoprocessing operation and might make sense as a part of pygeoprocessing, we should be sure to talk about that with Rich as the pygeoprocessing maintainer.  Does that sound right?

And for my part, I'm sorry about complicating things with `delineateit` here and creating all this extra work for everyone, and thanks for working through this discussion.
